const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const state = { student: JSON.parse(localStorage.getItem('ielts-student') || '{}') };
const app = $('#app');

function toast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),2200); }
function graphImage(graph){ return `assets/graphs/g${String(graph.id).padStart(2,'0')}${graph.id===4||graph.id===7||graph.id===20?'.png':graph.id===15?'b.jpg':'.jpg'}`; }
function draftKey(id){ return `ielts-graph-${id}`; }
function loadDraft(id){ return JSON.parse(localStorage.getItem(draftKey(id)) || '{"answers":{},"patterns":{}}'); }
function saveDraft(id,draft){ localStorage.setItem(draftKey(id),JSON.stringify(draft)); updateProgress(); }
function completedCount(){ return GRAPHS.filter(g=>{const d=loadDraft(g.id);return SECTION_DEFINITIONS.every(s=>(d.answers?.[s.id]||'').trim().length>8)}).length; }
function updateProgress(){ $('#global-progress').textContent=`${completedCount()} / ${GRAPHS.length} practised`; }
function escapeHtml(value=''){ return value.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }

function renderHome(){
  document.title='IELTS Graph Writing Studio';
  app.innerHTML=`<section class="hero"><p class="eyebrow">Academic Writing Task 1</p><h1>Read the graph.<br>Build the language.</h1><p class="hero-copy">Choose a real practice graph, select a sentence frame, then shape it around the data. Your six sections become one complete response.</p><div class="hero-stats"><div><strong>${GRAPHS.length}</strong><span>practice graphs</span></div><div><strong>6</strong><span>guided sections</span></div><div><strong>60</strong><span>sentence patterns</span></div></div></section><section class="dashboard"><div class="toolbar"><input class="search" id="search" type="search" placeholder="Search graphs, years or topics…" aria-label="Search graphs"><select class="filter" id="filter" aria-label="Filter graph type"><option value="all">All graph styles</option><option value="line">Line graphs</option><option value="bar">Bar charts</option><option value="projection">Projections</option></select></div><div class="graph-grid" id="graph-grid"></div></section>`;
  const draw=()=>{const q=$('#search').value.toLowerCase();const f=$('#filter').value;const rows=GRAPHS.filter(g=>(f==='all'||g.tags.includes(f))&&`${g.title} ${g.years} ${g.prompt}`.toLowerCase().includes(q));$('#graph-grid').innerHTML=rows.length?rows.map(cardHtml).join(''):'<p class="empty">No graphs match that search.</p>';};
  $('#search').addEventListener('input',draw);$('#filter').addEventListener('change',draw);draw();
}
function cardHtml(g){const complete=SECTION_DEFINITIONS.every(s=>(loadDraft(g.id).answers?.[s.id]||'').trim().length>8);return `<article class="graph-card"><div class="thumb-wrap"><img src="${graphImage(g)}" alt="${escapeHtml(g.title)} graph" loading="lazy"><span class="card-number">GRAPH ${String(g.id).padStart(2,'0')}</span>${complete?'<span class="complete-mark" title="Completed">✓</span>':''}</div><div class="card-body"><h3>${escapeHtml(g.title)}</h3><div class="meta">${escapeHtml(g.years)} · ${escapeHtml(g.metric)}</div><div class="tags">${g.tags.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')}</div><a class="start-link" href="#/graph/${g.id}">${complete?'Continue practice':'Start practice'} →</a></div></article>`;}

function renderPractice(id){
  const g=GRAPHS.find(x=>x.id===Number(id));if(!g){location.hash='#/';return;} const draft=loadDraft(g.id);
  document.title=`Graph ${g.id}: ${g.title}`;
  app.innerHTML=`<div class="practice-shell"><nav class="breadcrumbs"><a href="#/">All graphs</a><span>›</span><span>Graph ${String(g.id).padStart(2,'0')}</span></nav><div class="practice-grid"><aside class="graph-panel"><img src="${graphImage(g)}" alt="${escapeHtml(g.title)}"><h1>${escapeHtml(g.title)}</h1><p class="prompt">${escapeHtml(g.prompt)}</p><div class="coach-tip"><strong>Coach’s focus</strong><br>${escapeHtml(g.hint)}</div></aside><section><div class="section-stack">${SECTION_DEFINITIONS.map((s,i)=>sectionHtml(g,s,draft,i===0)).join('')}</div><div class="review-bar"><p><strong>Ready for a complete review?</strong>Complete all six sections, then send the response for feedback and teacher recording.</p><button class="primary-button" id="full-review">Review full response</button></div><div id="full-results" class="results-panel hidden"></div></section></div></div>`;
  bindPractice(g,draft);
}
function sectionHtml(g,s,draft,open){const answer=draft.answers?.[s.id]||'';const selected=draft.patterns?.[s.id]??0;const colors={blue:'#4169a1',violet:'#7955a1',green:'#228765',orange:'#c8782d',pink:'#b94b76',teal:'#16858b'};return `<article class="practice-section ${open?'open':''}" data-section="${s.id}" style="--section:${colors[s.color]}"><button class="section-toggle" type="button" aria-expanded="${open}"><span class="section-number">${s.number}</span><span class="section-title"><strong>${s.title}</strong><small>${s.subtitle}</small></span><span class="section-status ${answer.trim().length>8?'done':''}"></span><span class="chevron">⌄</span></button><div class="section-body"><p class="patterns-label">Choose a sentence pattern</p><div class="pattern-list">${s.patterns.map((p,i)=>`<button type="button" class="pattern-chip ${i===selected?'active':''}" data-pattern="${i}">Pattern ${i+1}</button>`).join('')}</div><div class="pattern-preview">${escapeHtml(s.patterns[selected])}</div><label class="answer-label" for="answer-${s.id}">Your sentence <span class="word-count">${wordCount(answer)} words</span></label><textarea id="answer-${s.id}" placeholder="Adapt the pattern using exact details from this graph…">${escapeHtml(answer)}</textarea><div class="section-actions"><button type="button" class="primary-button section-review">Check this section</button><button type="button" class="secondary-button use-pattern">Use pattern</button></div><div class="section-feedback"></div></div></article>`;}
function wordCount(text){return (text.trim().match(/\b[\w’'-]+\b/g)||[]).length;}
function bindPractice(g,draft){
  $$('.practice-section').forEach(card=>{
    const section=SECTION_DEFINITIONS.find(s=>s.id===card.dataset.section);const textarea=$('textarea',card);
    $('.section-toggle',card).addEventListener('click',()=>{card.classList.toggle('open');$('.section-toggle',card).setAttribute('aria-expanded',card.classList.contains('open'));});
    $$('.pattern-chip',card).forEach(chip=>chip.addEventListener('click',()=>{$$('.pattern-chip',card).forEach(c=>c.classList.remove('active'));chip.classList.add('active');draft.patterns[section.id]=Number(chip.dataset.pattern);$('.pattern-preview',card).textContent=section.patterns[chip.dataset.pattern];saveDraft(g.id,draft);}));
    $('.use-pattern',card).addEventListener('click',()=>{if(textarea.value.trim()&&!confirm('Replace your current sentence with the selected pattern?'))return;textarea.value=$('.pattern-preview',card).textContent;textarea.focus();textarea.dispatchEvent(new Event('input'));});
    textarea.addEventListener('input',()=>{draft.answers[section.id]=textarea.value;$('.word-count',card).textContent=`${wordCount(textarea.value)} words`;$('.section-status',card).classList.toggle('done',textarea.value.trim().length>8);saveDraft(g.id,draft);});
    $('.section-review',card).addEventListener('click',()=>renderLocalFeedback(card,section,textarea.value,g.sample[SECTION_DEFINITIONS.indexOf(section)]));
  });
  $('#full-review').addEventListener('click',()=>reviewAll(g,draft));
}
function localChecks(text,section){const notes=[];const t=text.trim();if(!t)return ['Write a sentence before requesting feedback.'];if(!/^[A-Z]/.test(t))notes.push('Begin the sentence with a capital letter.');if(!/[.!?]$/.test(t))notes.push('Add final punctuation.');if(/\b(increased|decreased|rose|fell) from\b[^.]+\bby\b/i.test(t))notes.push('Check “from … to …” versus “by …”: use “to” for the final value and “by” for the amount of change.');if(/\b(percentage|number) of\b[^.]+\bwere\b/i.test(t))notes.push('Check subject–verb agreement: “the percentage/number … was,” unless the plural noun is the subject.');if(/\b(people|students|tourists) was\b/i.test(t))notes.push('Use a plural verb with this plural subject (“were,” not “was”).');if(/\bmore higher|more lower|most highest|most lowest\b/i.test(t))notes.push('Avoid double comparatives such as “more higher” or “most highest.”');if(section.id==='overview'&&!/overall|main feature|stand out/i.test(t))notes.push('Signal that this is an overview with “Overall” or another overview phrase.');if(/\[[^\]]+\]/.test(t))notes.push('Replace every [placeholder] with information from the graph.');if(wordCount(t)<8)notes.push('Develop the idea with a category, figure and/or time reference.');return notes;}
function renderLocalFeedback(card,section,text,model){const notes=localChecks(text,section);const box=$('.section-feedback',card);box.innerHTML=`<div class="feedback-box ${notes.length?'warn':''}"><strong>${notes.length?'Points to revise':'Strong first check'}</strong><br>${notes.length?notes.map(n=>`• ${escapeHtml(n)}`).join('<br>'):'No common mechanical problems were detected. Check every number against the graph.'}</div><div class="model-box"><strong>Model using this section’s approach</strong><br>${escapeHtml(model)}</div>`;}
async function reviewAll(g,draft){
  const answers=Object.fromEntries(SECTION_DEFINITIONS.map(s=>[s.id,(draft.answers?.[s.id]||'').trim()]));const missing=SECTION_DEFINITIONS.filter(s=>!answers[s.id]);if(missing.length){toast(`Complete ${missing.length} more section${missing.length>1?'s':''} first.`);return;}
  if(!state.student.name){openStudentDialog();toast('Add your name before submitting.');return;}
  const button=$('#full-review');button.disabled=true;button.textContent='Reviewing…';
  const offline=SECTION_DEFINITIONS.flatMap(s=>localChecks(answers[s.id],s).map(note=>`${s.number} ${s.title}: ${note}`));let result={score:null,summary:offline.length?offline.join('\n'):'Your response passed the offline mechanical checks. Verify all data carefully.',model:g.sample.join('\n\n'),saved:false,mode:'offline'};
  if(SITE_CONFIG.reviewEndpoint){try{const response=await fetch(SITE_CONFIG.reviewEndpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'review',accessCode:state.student.accessCode||'',studentName:state.student.name,graph:{id:g.id,title:g.title,prompt:g.prompt,hint:g.hint},answers,patterns:draft.patterns,offlineNotes:offline})});if(!response.ok)throw new Error('Review service unavailable');const remote=await response.json();if(remote.error)throw new Error(remote.error);result=remote;}catch(error){toast('AI service unavailable — showing offline feedback.');}}
  const panel=$('#full-results');panel.classList.remove('hidden');panel.innerHTML=`<h2>Your complete review</h2>${result.score!=null?`<div class="score">${escapeHtml(String(result.score))}<small>/9</small></div>`:''}<p>${escapeHtml(result.summary||result.feedback||'Review complete.').replace(/\n/g,'<br>')}</p><h3>Model response using the same section structure</h3><div class="submission-text">${escapeHtml(result.model||g.sample.join('\n\n'))}</div><p class="meta">${result.saved?'✓ Saved to your teacher’s Google Drive record.':'Offline mode: this attempt has not been sent to Google Drive.'}</p>`;panel.scrollIntoView({behavior:'smooth',block:'start'});draft.submittedAt=new Date().toISOString();saveDraft(g.id,draft);button.disabled=false;button.textContent='Review full response';
}
function openStudentDialog(){ $('#student-name').value=state.student.name||'';$('#access-code').value=state.student.accessCode||'';$('#student-dialog').showModal(); }
$('#student-button').addEventListener('click',openStudentDialog);
$('#student-form').addEventListener('submit',e=>{if(e.submitter?.value!=='save')return;state.student={name:$('#student-name').value.trim(),accessCode:$('#access-code').value};localStorage.setItem('ielts-student',JSON.stringify(state.student));toast('Student details saved.');});
function route(){const match=location.hash.match(/^#\/graph\/(\d+)/);match?renderPractice(match[1]):renderHome();updateProgress();window.scrollTo(0,0);}window.addEventListener('hashchange',route);route();
