const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const state = { student: JSON.parse(localStorage.getItem('ielts-student') || '{}') };
const app = $('#app');

function toast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),2200); }
function graphImages(graph){if(graph.images?.length)return graph.images;return [{src:`assets/graphs/g${String(graph.id).padStart(2,'0')}${graph.id===4||graph.id===7||graph.id===20?'.png':graph.id===15?'b.jpg':'.jpg'}`,alt:`${graph.title} graph`}];}
function graphImage(graph){return graphImages(graph)[0].src;}
function draftKey(id){ return `ielts-graph-${id}`; }
function loadDraft(id){ return JSON.parse(localStorage.getItem(draftKey(id)) || '{"answers":{},"patterns":{}}'); }
function saveDraft(id,draft){ localStorage.setItem(draftKey(id),JSON.stringify(draft)); updateProgress(); }
function sectionsFor(graph){return graph.sections||SECTION_DEFINITIONS;}
function completedCount(){ return GRAPHS.filter(g=>{const d=loadDraft(g.id);return sectionsFor(g).every(s=>(d.answers?.[s.id]||'').trim().length>8)}).length; }
function updateProgress(){ $('#global-progress').textContent=`${completedCount()} / ${GRAPHS.length} practised`; }
function escapeHtml(value=''){ return value.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }

function renderHome(){
  document.title='IELTS Graph Writing Studio';
  app.innerHTML=`<section class="hero"><p class="eyebrow">Academic Writing Task 1</p><h1>Read the graph.<br>Build the language.</h1><p class="hero-copy">Choose a real practice graph, select a sentence frame, then shape it around the data. Your six sections become one complete response.</p><div class="hero-stats"><div><strong>${GRAPHS.length}</strong><span>practice graphs</span></div><div><strong>6</strong><span>guided sections</span></div><div><strong>60</strong><span>sentence patterns</span></div></div></section><section class="dashboard"><div class="toolbar"><input class="search" id="search" type="search" placeholder="Search graphs, years or topics…" aria-label="Search graphs"><select class="filter" id="filter" aria-label="Filter graph type"><option value="all">All graph styles</option><option value="line">Line graphs</option><option value="bar">Bar charts</option><option value="projection">Projections</option></select></div><div class="graph-grid" id="graph-grid"></div></section>`;
  const draw=()=>{const q=$('#search').value.toLowerCase();const f=$('#filter').value;const rows=GRAPHS.filter(g=>(f==='all'||g.tags.includes(f))&&`${g.title} ${g.years} ${g.prompt}`.toLowerCase().includes(q));$('#graph-grid').innerHTML=rows.length?rows.map(cardHtml).join(''):'<p class="empty">No graphs match that search.</p>';};
  $('#search').addEventListener('input',draw);$('#filter').addEventListener('change',draw);draw();
}
function cardHtml(g){const complete=sectionsFor(g).every(s=>(loadDraft(g.id).answers?.[s.id]||'').trim().length>8);return `<article class="graph-card"><div class="thumb-wrap"><img src="${graphImage(g)}" alt="${escapeHtml(g.title)} graph" loading="lazy"><span class="card-number">GRAPH ${String(g.id).padStart(2,'0')}</span>${complete?'<span class="complete-mark" title="Completed">✓</span>':''}</div><div class="card-body"><h3>${escapeHtml(g.title)}</h3><div class="meta">${escapeHtml(g.years)} · ${escapeHtml(g.metric)}</div><div class="tags">${g.tags.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')}</div><a class="start-link" href="#/graph/${g.id}">${complete?'Continue practice':'Start practice'} →</a></div></article>`;}

function renderPractice(id){
  const g=GRAPHS.find(x=>x.id===Number(id));if(!g){location.hash='#/';return;} const draft=loadDraft(g.id);const sections=sectionsFor(g);
  document.title=`Graph ${g.id}: ${g.title}`;
  app.innerHTML=`<div class="practice-shell"><nav class="breadcrumbs"><a href="#/">All graphs</a><span>›</span><span>Graph ${String(g.id).padStart(2,'0')}</span></nav><div class="practice-grid"><aside class="graph-panel"><div class="graph-images">${graphImages(g).map((image,i)=>`<figure><img src="${image.src}" alt="${escapeHtml(image.alt||g.title)}">${image.caption?`<figcaption>${escapeHtml(image.caption)}</figcaption>`:''}</figure>`).join('')}</div><h1>${escapeHtml(g.title)}</h1><p class="prompt">${escapeHtml(g.prompt)}</p>${g.source?`<a class="source-link" href="${g.source}" target="_blank" rel="noopener">View source data ↗</a>`:''}<div class="coach-tip"><strong>Coach’s focus</strong><br>${escapeHtml(g.hint)}</div></aside><section><div class="section-stack">${sections.map((s,i)=>sectionHtml(g,s,draft,i===0)).join('')}</div><div class="review-bar"><p><strong>Ready for a complete review?</strong>Complete all six sections, then send the response for feedback and teacher recording.</p><button class="primary-button" id="full-review">Review full response</button></div><div id="full-results" class="results-panel hidden"></div></section></div></div>`;
  bindPractice(g,draft,sections);
}
function sectionHtml(g,s,draft,open){const answer=draft.answers?.[s.id]||'';const selected=draft.patterns?.[s.id]??0;const colors={blue:'#4169a1',violet:'#7955a1',green:'#228765',orange:'#c8782d',pink:'#b94b76',teal:'#16858b'};return `<article class="practice-section ${open?'open':''}" data-section="${s.id}" style="--section:${colors[s.color]}"><button class="section-toggle" type="button" aria-expanded="${open}"><span class="section-number">${s.number}</span><span class="section-title"><strong>${s.title}</strong><small>${s.subtitle}</small></span><span class="section-status ${answer.trim().length>8?'done':''}"></span><span class="chevron">⌄</span></button><div class="section-body"><p class="patterns-label">Choose a sentence pattern</p><div class="pattern-list">${s.patterns.map((p,i)=>`<button type="button" class="pattern-chip ${i===selected?'active':''}" data-pattern="${i}">Pattern ${i+1}</button>`).join('')}</div><div class="pattern-preview">${escapeHtml(s.patterns[selected])}</div><label class="answer-label" for="answer-${s.id}">Your sentence <span class="word-count">${wordCount(answer)} words</span></label><textarea id="answer-${s.id}" placeholder="Adapt the pattern using exact details from this graph…">${escapeHtml(answer)}</textarea><div class="section-actions"><button type="button" class="primary-button section-review">Check this section</button><button type="button" class="secondary-button use-pattern">Use pattern</button></div><div class="section-feedback"></div></div></article>`;}
function wordCount(text){return (text.trim().match(/\b[\w’'-]+\b/g)||[]).length;}
function bindPractice(g,draft,sections){
  $$('.practice-section').forEach(card=>{
    const section=sections.find(s=>s.id===card.dataset.section);const textarea=$('textarea',card);
    $('.section-toggle',card).addEventListener('click',()=>{card.classList.toggle('open');$('.section-toggle',card).setAttribute('aria-expanded',card.classList.contains('open'));});
    $$('.pattern-chip',card).forEach(chip=>chip.addEventListener('click',()=>{$$('.pattern-chip',card).forEach(c=>c.classList.remove('active'));chip.classList.add('active');draft.patterns[section.id]=Number(chip.dataset.pattern);$('.pattern-preview',card).textContent=section.patterns[chip.dataset.pattern];saveDraft(g.id,draft);}));
    $('.use-pattern',card).addEventListener('click',()=>{if(textarea.value.trim()&&!confirm('Replace your current sentence with the selected pattern?'))return;textarea.value=$('.pattern-preview',card).textContent;textarea.focus();textarea.dispatchEvent(new Event('input'));});
    textarea.addEventListener('input',()=>{draft.answers[section.id]=textarea.value;$('.word-count',card).textContent=`${wordCount(textarea.value)} words`;$('.section-status',card).classList.toggle('done',textarea.value.trim().length>8);saveDraft(g.id,draft);});
    $('.section-review',card).addEventListener('click',()=>reviewSection(card,section,textarea.value,g,g.sample[sections.indexOf(section)]));
    textarea.addEventListener('input',()=>{const feedback=$('.section-feedback',card);if(feedback.innerHTML)feedback.innerHTML='<p class="feedback-stale">Sentence changed — check it again for updated corrections.</p>';});
  });
  $('#full-review').addEventListener('click',()=>reviewAll(g,draft,sections));
}
function analyseLocal(text,section){return GrammarChecker.analyse(text,{sectionId:section.id});}
function normaliseIssue(issue,sectionTitle){return {section:issue.section||sectionTitle||'',category:issue.category||'Grammar',original:issue.original||'',corrected:issue.corrected||issue.replacement||'',explanation:issue.explanation||issue.message||'Revise this part.',kind:issue.kind||(issue.severity==='style'?'style':'grammar')};}
function mergeIssues(localIssues,remoteIssues,sectionTitle){const merged=[];const keys=new Set();[...(localIssues||[]),...(remoteIssues||[])].forEach(raw=>{const issue=normaliseIssue(raw,sectionTitle);const key=`${issue.section}|${issue.category}|${issue.original}|${issue.corrected}`.toLowerCase();if(!keys.has(key)){keys.add(key);merged.push(issue);}});return merged;}
function issueListHtml(issues){if(!issues.length)return '';return `<ol class="issue-list">${issues.map(issue=>`<li class="issue-card ${issue.kind==='style'?'style-issue':''}">${issue.section?`<span class="issue-section">${escapeHtml(issue.section)}</span>`:''}<span class="issue-category">${escapeHtml(issue.category)}</span><div class="phrase-comparison"><span><small>Original</small><del>${escapeHtml(issue.original)}</del></span><b aria-hidden="true">→</b><span><small>Correction</small><ins>${escapeHtml(issue.corrected)}</ins></span></div><p class="issue-explanation">${escapeHtml(issue.explanation)}</p></li>`).join('')}</ol>`;}
function grammarFeedbackHtml(review,model,options={}){const issues=(review.issues||[]).map(i=>normaliseIssue(i,options.sectionTitle));const grammar=issues.filter(i=>i.kind!=='style');const style=issues.filter(i=>i.kind==='style');const source=options.source||'instant';const aiReviewed=source==='ai';const statusClass=grammar.length?'needs-revision':aiReviewed?'correct':'caution';const heading=grammar.length?`${grammar.length} grammar ${grammar.length===1?'issue':'issues'} found`:aiReviewed?'AI review found no clear grammar errors':'No matching quick-check rule found';const statusText=grammar.length?'Corrections are shown in red.':aiReviewed?'Check the graph data and meaning carefully.':'This does not confirm that the sentence is grammatically correct.';const limitation=source==='offline'?'<p class="review-limitation"><strong>Important:</strong> this is a limited on-device check. The teacher AI service is not connected, so errors outside the listed rules may be missed.</p>':'';return `<section class="grammar-review ${statusClass}" aria-live="polite"><div class="review-summary"><strong>${heading}</strong><span>${statusText}</span></div>${issueListHtml(grammar)}${review.correctedSentence&&grammar.length?`<div class="corrected-sentence"><strong>Corrected sentence</strong><p>${escapeHtml(review.correctedSentence)}</p></div>`:''}${style.length?`<div class="style-heading"><strong>IELTS style improvements</strong><span>These are improvements, not grammar errors.</span></div>${issueListHtml(style)}`:''}${limitation}</section>${review.summary?`<div class="ai-summary"><strong>${source==='ai'?'AI teacher note':'Grammar note'}</strong><p>${escapeHtml(review.summary)}</p></div>`:''}<div class="model-box"><strong>Model using this section’s approach</strong><br>${escapeHtml(model)}</div>`;}
async function reviewSection(card,section,text,g,model){const box=$('.section-feedback',card);const local=analyseLocal(text,section);if(!text.trim()){box.innerHTML=grammarFeedbackHtml(local,model,{source:'offline',sectionTitle:section.title});return;}box.innerHTML=grammarFeedbackHtml(local,model,{source:SITE_CONFIG.reviewEndpoint?'instant':'offline',sectionTitle:section.title});if(!SITE_CONFIG.reviewEndpoint)return;if(!state.student.accessCode){box.insertAdjacentHTML('afterbegin','<p class="review-limitation">Add your class/access code under Student details to run the AI grammar review.</p>');return;}const button=$('.section-review',card);button.disabled=true;button.textContent='Checking grammar…';card.setAttribute('aria-busy','true');try{const response=await fetch(SITE_CONFIG.reviewEndpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'reviewSection',accessCode:state.student.accessCode,studentName:state.student.name||'Student',graph:{id:g.id,title:g.title,prompt:g.prompt,hint:g.hint,referenceModel:g.sample},section:{id:section.id,title:section.title,pattern:$('.pattern-preview',card).textContent},text,offlineAnalysis:local})});if(!response.ok)throw new Error('Review service unavailable');const remote=await response.json();if(remote.error)throw new Error(remote.error);remote.issues=mergeIssues(local.issues,remote.issues,section.title);remote.correctedSentence=remote.correctedSentence||local.correctedSentence;box.innerHTML=grammarFeedbackHtml(remote,model,{source:'ai',sectionTitle:section.title});}catch(error){box.innerHTML=grammarFeedbackHtml(local,model,{source:'offline',sectionTitle:section.title});box.insertAdjacentHTML('afterbegin','<p class="review-limitation">AI grammar review is unavailable. The corrections below come from the on-device checker.</p>');}finally{button.disabled=false;button.textContent='Check this section';card.removeAttribute('aria-busy');}}
async function reviewAll(g,draft,sections=SECTION_DEFINITIONS){
  const answers=Object.fromEntries(sections.map(s=>[s.id,(draft.answers?.[s.id]||'').trim()]));const missing=sections.filter(s=>!answers[s.id]);if(missing.length){toast(`Complete ${missing.length} more section${missing.length>1?'s':''} first.`);return;}
  if(!state.student.name){openStudentDialog();toast('Add your name before submitting.');return;}
  const button=$('#full-review');button.disabled=true;button.textContent='Reviewing…';
  const offlineBySection=sections.map(s=>({sectionId:s.id,sectionTitle:s.title,...analyseLocal(answers[s.id],s)}));const offlineIssues=offlineBySection.flatMap(item=>item.issues.map(issue=>({...issue,section:item.sectionTitle})));let result={score:null,summary:'The complete response received the on-device grammar check. Connect the teacher AI service for IELTS scoring and deeper feedback.',issues:offlineIssues,correctedResponse:offlineBySection.map(item=>item.correctedSentence).join('\n\n'),model:g.sample.join('\n\n'),saved:false,mode:'offline'};
  const selectedPatterns=Object.fromEntries(sections.map(s=>[s.id,s.patterns[draft.patterns?.[s.id]??0]]));const sectionTitles=Object.fromEntries(sections.map(s=>[s.id,s.title]));if(SITE_CONFIG.reviewEndpoint){try{const response=await fetch(SITE_CONFIG.reviewEndpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'review',accessCode:state.student.accessCode||'',studentName:state.student.name,graph:{id:g.id,title:g.title,prompt:g.prompt,hint:g.hint,referenceModel:g.sample},answers,selectedPatterns,sectionTitles,offlineAnalysis:offlineBySection})});if(!response.ok)throw new Error('Review service unavailable');const remote=await response.json();if(remote.error)throw new Error(remote.error);remote.issues=mergeIssues(offlineIssues,remote.issues);result={...result,...remote,issues:remote.issues,mode:'ai'};}catch(error){toast('AI service unavailable — showing on-device corrections.');}}
  const panel=$('#full-results');const allIssues=(result.issues||[]).map(i=>normaliseIssue(i));const grammarIssues=allIssues.filter(i=>i.kind!=='style');const styleIssues=allIssues.filter(i=>i.kind==='style');panel.classList.remove('hidden');panel.innerHTML=`<h2>Your complete review</h2>${result.score!=null?`<div class="score">${escapeHtml(String(result.score))}<small>/9</small></div>`:''}<p>${escapeHtml(result.summary||result.feedback||'Review complete.').replace(/\n/g,'<br>')}</p>${grammarIssues.length?`<h3 class="corrections-title">Grammar corrections</h3>${issueListHtml(grammarIssues)}`:`<div class="feedback-box ${result.mode==='ai'?'':'warn'}"><strong>${result.mode==='ai'?'AI review found no clear grammar errors.':'No matching quick-check rule found.'}</strong><br>${result.mode==='ai'?'Check data accuracy and task achievement carefully.':'This limited on-device result does not confirm that the response is error-free.'}</div>`}${result.correctedResponse&&grammarIssues.length?`<div class="corrected-sentence full"><strong>Corrected complete response</strong><p>${escapeHtml(result.correctedResponse)}</p></div>`:''}${styleIssues.length?`<h3>IELTS style improvements</h3>${issueListHtml(styleIssues)}`:''}<h3>Model response using the same section structure</h3><div class="submission-text">${escapeHtml(result.model||g.sample.join('\n\n'))}</div><p class="meta">${result.saved?'✓ Saved to your teacher’s Google Drive record.':'Offline mode: this attempt has not been sent to Google Drive.'}</p>`;panel.scrollIntoView({behavior:'smooth',block:'start'});draft.submittedAt=new Date().toISOString();saveDraft(g.id,draft);button.disabled=false;button.textContent='Review full response';
}
function openStudentDialog(){ $('#student-name').value=state.student.name||'';$('#access-code').value=state.student.accessCode||'';$('#student-dialog').showModal(); }
$('#student-button').addEventListener('click',openStudentDialog);
$('#student-form').addEventListener('submit',e=>{if(e.submitter?.value!=='save')return;state.student={name:$('#student-name').value.trim(),accessCode:$('#access-code').value};localStorage.setItem('ielts-student',JSON.stringify(state.student));toast('Student details saved.');});
function route(){const match=location.hash.match(/^#\/graph\/(\d+)/);match?renderPractice(match[1]):renderHome();updateProgress();window.scrollTo(0,0);}window.addEventListener('hashchange',route);route();
