const SECTION_DEFINITIONS = [
  {
    id: 'introduction', number: '01', title: 'Introduction', subtitle: 'Paraphrase what the graph shows', color: 'blue',
    patterns: [
      'The given [chart type] illustrates the [number/percentage] of [categories] in [place], from [year 1] to [year 2].',
      'The [chart type] shows the [metric] of [categories], divided into [number] groups, in [place] from [year 1] to [year 2].',
      'The [chart type] compares the [metric] of [A] and [B] in [place] over a period of [number] years, from [year 1] to [year 2].',
      'The [chart type] depicts the figures for [categories] in [place] between [year 1] and [year 2].',
      'The [chart type] gives information about the [metric] of [categories] in [place] during the [year 1]–[year 2] period.',
      '[Metric] for [categories] in [place] from [year 1] to [year 2] is shown in the [chart type].',
      'The [chart type] illustrates the changes in [metric] for [categories] in [place] from [year 1] to [year 2].',
      'The [chart type] shows the average [metric] in [number] [cities/places] throughout the year.',
      'The [chart type] illustrates the projected [metric] for [categories] in [place] from [year 1] to [year 2].',
      'The [chart type] presents the [metric] for [categories] over a [number]-year period, commencing in [year 1].'
    ]
  },
  {
    id: 'overview', number: '02', title: 'Two general trends', subtitle: 'Select the two most important features', color: 'violet',
    patterns: [
      'Overall, [A] remained the highest throughout the period, while [B] remained the lowest.',
      '[A] consistently recorded the highest [metric] across the entire period, whereas [B] consistently recorded the lowest.',
      '[A] overtook [B] in around [year], and remained higher for the rest of the period.',
      '[B] was overtaken by [A] in around [year], having previously been the higher of the two.',
      '[A] and [B] showed a clear upward trend over the period, while [C] and [D] displayed a downward trend.',
      'There was a marked increase in [metric] for [A]; in contrast, [B] saw a marked decrease.',
      '[A] reached its highest point in [year], before declining for the remainder of the period.',
      'Although [A] fluctuated throughout the period, it reached a peak of [number] in [year] and a low of [number] in [year].',
      '[A] remained relatively stable across the period, in sharp contrast to [B], which fluctuated considerably.',
      'Two main features stand out from the graph: firstly, [trend 1]; secondly, [trend 2].'
    ]
  },
  {
    id: 'upward', number: '03', title: 'Upward trend', subtitle: 'Connect rising categories and quantify them', color: 'green',
    patterns: [
      '[A] [rose/increased/climbed] [steadily/sharply] from [number 1] to [number 2] [unit] over the period.',
      'A similarly [steady/sharp] upward trend can be seen in [B], which [rose/climbed] from [number 1] to [number 2].',
      'Likewise, [B] [increased/climbed] from [number 1] to [number 2], mirroring the pattern seen in [A].',
      'In the same way, [B] also increased, climbing from [number 1] to [number 2] by [year 2].',
      '[A] rose steadily, growing from [number 1] to [number 2] between [year 1] and [year 2].',
      'Both [A] and [B] followed a similarly steep upward trajectory, rising from [number 1] and [number 1b] to [number 2] and [number 2b] respectively.',
      '[A] more than [doubled/tripled], surging from [number 1] to [number 2] by [year 2].',
      'As with [A], [B] also trended upwards, climbing from [number 1] to [number 2] by [year 2].',
      '[A] rose by [number] percentage points, from [number 1]% to [number 2]%, between [year 1] and [year 2].',
      'While [A] rose steadily, a more dramatic rise was also recorded for [B], from [number 1] to [number 2].'
    ]
  },
  {
    id: 'downward', number: '04', title: 'Downward trend', subtitle: 'Connect falling categories and quantify them', color: 'orange',
    patterns: [
      '[A] [fell/decreased/declined] [steadily/sharply] from [number 1] to [number 2] [unit] over the period.',
      'A similarly [steady/sharp] downward trend can be seen in [B], which [fell/dropped] from [number 1] to [number 2].',
      'Likewise, [B] declined from [number 1] to [number 2], mirroring the pattern seen in [A].',
      'In the same way, [B] also decreased, falling from [number 1] to [number 2] by [year 2].',
      '[A] fell steadily, dropping from [number 1] to [number 2] between [year 1] and [year 2].',
      'Both [A] and [B] followed a similarly steep downward trajectory, falling from [number 1] and [number 1b] to [number 2] and [number 2b] respectively.',
      '[A] more than halved, plunging from [number 1] to [number 2] by [year 2].',
      'As with [A], [B] also trended downwards, dropping from [number 1] to [number 2] by [year 2].',
      '[A] fell by [number] percentage points, from [number 1]% to [number 2]%, between [year 1] and [year 2].',
      'While [A] declined gradually, a steeper decline was also recorded for [B], from [number 1] to [number 2].'
    ]
  },
  {
    id: 'fluctuation', number: '05', title: 'Fluctuation', subtitle: 'Break one changing line into phases', color: 'pink',
    patterns: [
      '[A] fluctuated considerably: it rose from [number 1] to [number 2] by [year 2], before falling back to [number 3] by [year 3].',
      'After climbing from [number 1] to [number 2] between [year 1] and [year 2], [A] then fell back to [number 3] by [year 3].',
      '[A] rose to a peak of [number 2] in [year 2], before falling back to [number 3] by [year 3].',
      '[A] fell to a low of [number 2] in [year 2], before recovering to [number 3] by [year 3].',
      '[A]’s figures moved in an irregular pattern, rising and falling repeatedly between [number 1] and [number 2] throughout the period.',
      'There were three distinct phases in [A]’s trend: a rise from [number 1] to [number 2], followed by a decline, and finally a recovery to [number 4].',
      'Although [A] rose initially, reaching [number 2] by [year 2], this was followed by a reversal, dropping to [number 3] by [year 3].',
      '[A] remained broadly stable until [year 2], when it suddenly [rose/fell], before levelling off at [number 3].',
      'The most striking feature of [A] is its volatility: [number 1] in [year 1] rose to [number 2] in [year 2], then dropped to [number 3] and rose again to [number 4].',
      'Overall, [A] showed no consistent direction, ending at [number 2], close to its starting point of [number 1], despite considerable fluctuation in between.'
    ]
  },
  {
    id: 'conclusion', number: '06', title: 'Conclusion & indication', subtitle: 'Make a careful, hedged inference', color: 'teal',
    patterns: [
      'If this trend continues, [A] is likely to [verb] [number] by [future year].',
      'Should [A] carry on [verb-ing] at the same rate, it may [overtake/fall below] [B] within the next [number] years.',
      'This [rise/fall] in [A] may be attributable to [plausible cause], although the data alone does not confirm this.',
      'The [pattern] observed in [A] suggests that [inference].',
      'It seems likely that [A] will [verb] further in the coming years, given [reason drawn from the data].',
      'One plausible explanation for [A]’s [trend] is [cause]; however, other factors cannot be ruled out.',
      'Unless [condition changes], [A] is expected to [verb] [prediction] by [future year].',
      'The gap between [A] and [B] appears to be [narrowing/widening], which may indicate [inference].',
      'Overall, the data points to [general conclusion], a pattern that is likely to persist unless [condition].',
      'While it is not possible to say for certain, the figures indicate that [A] may [verb] in the near future.'
    ]
  }
];

const GRAPHS = [
  {id:1, title:'Weekly hospital admissions', years:'2004–2018', metric:'weekly admissions', tags:['line','5 series'], prompt:'Hospital admissions for five hospitals in a European country from 2004 to 2018.', hint:'Compare Bardley’s overall rise with Oxley’s decline; Stanton and Fortsmith fluctuate.', sample:['The line graph illustrates weekly admissions to five hospitals in a European country from 2004 to 2018.','Overall, Bardley recorded the highest figure for most of the period, whereas Stanton was generally among the lowest. Adlin rose overall, while Oxley declined markedly.','Bardley increased from about 200 to 270 admissions, and Adlin likewise climbed from roughly 120 to 250.','Oxley fell substantially from around 240 to 110 admissions over the period.','Fortsmith fluctuated between approximately 180 and 220, ending close to 200.','The contrasting paths may indicate changing demand across the five hospitals, although the graph does not identify the causes.']},
  {id:2, title:'Monthly city temperatures', years:'January–December', metric:'average temperature (°C)', tags:['line','seasonal'], prompt:'Average monthly temperatures in Paris, Boston and Melbourne.', hint:'Notice the opposite seasonal pattern in Melbourne and the higher summer peak in Boston.', sample:['The line graph compares average monthly temperatures in Paris, Boston and Melbourne throughout the year.','Overall, Boston showed the greatest seasonal variation, while Melbourne followed the opposite pattern to the two northern-hemisphere cities.','Boston surged from about 3°C in January to a peak of 31°C in August, while Paris climbed from 7°C to roughly 23°C.','Both then declined towards December, with Boston falling to around 4°C and Paris to 8°C.','Melbourne fell from 25°C to 15°C by July before recovering to 25°C in December.','The opposing cycles are likely to reflect the cities’ locations in different hemispheres.']},
  {id:3, title:'Students’ typical weekday', years:'single period', metric:'hours per day', tags:['bar','comparison'], prompt:'A typical weekday for students in the UK, Japan and Germany, divided into sleeping, studying and relaxing.', hint:'This is a comparison chart without a timeline, so focus on rankings rather than trends.', sample:['The bar chart compares the number of hours students in the UK, Japan and Germany spend sleeping, studying and relaxing on a typical weekday.','Overall, Japanese students study for by far the longest time, whereas UK students spend the most time sleeping and relaxing.','Study time stands at 13 hours in Japan, compared with 9 in Germany and 8 in the UK.','By contrast, Japanese students relax for only 4 hours, while the figure is 7 hours in both other countries.','As the chart has no time series, a fluctuation statement is not applicable.','The figures suggest that the Japanese students represented have a markedly more study-intensive weekday.']},
  {id:4, title:'US elderly leisure activities', years:'1980s–2010s', metric:'percentage participating', tags:['line','5 activities'], prompt:'Free-time activities of elderly people in the United States from the 1980s to the 2010s.', hint:'Hiking rises strongly; theatre and reading fluctuate; television remains popular.', sample:['The line graph illustrates the percentages of elderly Americans taking part in five leisure activities from the 1980s to the 2010s.','Overall, hiking experienced the strongest growth and became the most popular activity, while watching TV remained consistently popular.','Hiking quadrupled from 20% to 80%, and internet use rose from 5% to 50%.','Theatre attendance declined overall from 50% to 45%, despite a partial recovery after the 1990s.','Reading fell from 40% to 20% before rebounding sharply to 60% in the 2010s.','The pattern may indicate a broadening of leisure choices among older Americans.']},
  {id:5, title:'Cars manufactured', years:'2020–2035', metric:'hundreds of thousands of cars', tags:['line','projection'], prompt:'Estimated car production in China, the UK, Japan and the USA from 2020 to 2035.', hint:'China rises gradually while the other three countries decline, especially Japan after 2030.', sample:['The line graph presents estimated car production in four countries from 2020 to 2035.','Overall, China is the only country projected to grow, while Japan, the USA and the UK are all expected to decline.','China rises steadily from 100 to 150 hundred thousand cars.','The USA plunges from 300 to 20, while the UK falls from 200 to 40.','Japan edges up from 350 to 365 in 2025 before dropping sharply to 100 by 2035.','If these projections hold, China is likely to become the largest producer among the four countries by 2035.']},
  {id:6, title:'Scottish tourist attractions', years:'1980–2010', metric:'percentage of tourists', tags:['line','4 attractions'], prompt:'Percentages of tourists to Scotland who visited four types of attraction between 1980 and 2010.', hint:'The castle peaks in 1995; the aquarium falls overall; the zoo finishes higher.', sample:['The line graph depicts the percentages of tourists visiting four Scottish attractions between 1980 and 2010.','Overall, the castle became the leading attraction, whereas the aquarium declined to the lowest level by 2010.','Castle visits rose from about 23% to 45% in 1995, ending at roughly 33%; zoo visits increased overall from 10% to 20%.','Festival attendance declined gradually from 30% to 18%, while the aquarium fell overall from 20% to 9%.','Aquarium visits peaked at 35% in 1985 before dropping sharply to 20% in 1990.','The changes may reflect a shift in tourist preferences towards castles and zoos.']},
  {id:7, title:'Monthly city temperatures (large)', years:'January–December', metric:'average temperature (°C)', tags:['line','seasonal'], prompt:'Average monthly temperatures in Paris, Boston and Melbourne.', hint:'Use this clearer version to practise seasonal peaks, lows and contrasting hemispheres.', sample:['The line graph compares average temperatures in Paris, Boston and Melbourne across twelve months.','Overall, Boston was the warmest city in summer and showed the widest range, while Melbourne followed an inverse seasonal pattern.','Boston climbed from 3°C to 31°C by August, and Paris rose from 7°C to 23°C.','Both cities then cooled, finishing at approximately 4°C and 8°C respectively.','Melbourne declined steadily from 25°C to 15°C in July before recovering to its initial level.','These opposite patterns are likely to result from the cities being in different hemispheres.']},
  {id:8, title:'Patients at four hospital clinics', years:'2010–2016', metric:'weekly patients', tags:['line','4 clinics'], prompt:'Average weekly patient numbers for four clinics in a hospital from 2010 to 2016.', hint:'Dental rises most sharply; birth control falls then recovers; eye and diabetic clinics also grow.', sample:['The line graph shows average weekly patient numbers at four hospital clinics from 2010 to 2016.','Overall, dental care experienced the most dramatic rise, while birth control was the only service to fall before recovering.','Dental patients climbed from about 100 to 350, and diabetic-clinic attendance rose from roughly 60 to 180.','Birth-control visits declined from around 240 in 2010 to 180 in 2014.','They then recovered to approximately 240 by 2016, after an earlier peak of about 280.','The data may indicate rapidly growing demand for dental services at this hospital.']},
  {id:9, title:'Tourist information enquiries', years:'January–June 2011', metric:'number of enquiries', tags:['line','3 methods'], prompt:'Enquiries received by a city Tourist Information Office over six months in 2011.', hint:'In-person and telephone enquiries rise; letters and emails decline.', sample:['The line graph illustrates enquiries received by a city Tourist Information Office from January to June 2011.','Overall, in-person enquiries became the most common method, while letters and emails declined to the lowest figure.','In-person enquiries surged from about 450 to 1,900, and telephone enquiries rose from 900 to 1,600.','Letters and emails fell from roughly 750 to 350 over the period.','Telephone enquiries dipped to 800 in February, recovered to 1,000, levelled off, and then climbed again.','The change may indicate an increasing preference for immediate, direct communication.']},
  {id:10, title:'Future internet use', years:'2015–2030', metric:'usage index', tags:['line','projection'], prompt:'Projected changes in four uses of the internet between 2015 and 2030.', hint:'Shopping and online study rise; downloading films declines; email changes little.', sample:['The line graph presents projected changes in four internet activities from 2015 to 2030.','Overall, shopping is expected to become the leading activity, whereas downloading films is forecast to decline.','Shopping rises from 40 to about 95, while studying online grows from 35 to nearly 80.','Downloading films falls steadily from around 72 to below 50.','Sending emails remains broadly stable, edging up from 80 to approximately 87.','The projections point to a shift from downloading content towards interactive online services.']},
  {id:11, title:'World production output', years:'1840–2000', metric:'share of world output', tags:['bar','3 regions'], prompt:'Production output from Asia, Europe and the rest of the world in selected years.', hint:'Asia falls then recovers; Europe peaks in 1920; the rest of the world grows overall.', sample:['The bar chart compares production output from Asia, Europe and the rest of the world in five selected years.','Overall, Asia began and ended as the largest producer, while Europe peaked in 1920 before declining.','The rest of the world rose overall from 10 to 32, and Asia recovered from 20 in 1920 to 45 in 2000.','Europe fell from a peak of 50 in 1920 to 28 in 2000.','Asia declined from 50 to 20 before rebounding to 45, showing the clearest reversal.','The figures suggest a major long-term redistribution of production among the three regions.']},
  {id:12, title:'Facebook daily users', years:'2007–2014', metric:'daily users (millions)', tags:['line','3 countries'], prompt:'Active daily Facebook users in Vietnam, Cambodia and Thailand from 2007 to 2014.', hint:'Vietnam rises steadily; Thailand falls; Cambodia fluctuates dramatically.', sample:['The line graph compares daily Facebook users in Vietnam, Cambodia and Thailand from 2007 to 2014.','Overall, Vietnam rose steadily to become the largest market, while Thailand declined markedly; Cambodia was highly volatile.','Vietnam climbed fivefold from 5 million to 25 million users.','Thailand fell sharply from 25 million to 5 million.','Cambodia repeatedly rose and fell between 8 million and 18 million, ending at a peak of 18 million.','The diverging trends may indicate substantial differences in the adoption of Facebook across the three countries.']},
  {id:13, title:'CO₂ emissions by region', years:'2000–2040', metric:'millions of metric tonnes', tags:['line','projection'], prompt:'CO₂ emissions in five regions between 2000 and 2040.', hint:'Region 1 remains highest but falls; Region 3 rises overall; several series fluctuate.', sample:['The line graph presents CO₂ emissions in five regions between 2000 and 2040.','Overall, Region 1 remains the largest emitter despite declining, while Region 5 stays far below the others.','Region 3 rises overall from 4 to 6 million tonnes, and Region 4 grows from under 3 to about 5 million.','Region 1 falls from 8 to 7 million tonnes after peaking above 9 in 2010.','Region 5 fluctuates at a low level, reaching about 1.8 before falling and recovering slightly.','The narrowing gap may indicate a gradual redistribution of emissions among regions.']},
  {id:14, title:'Weekly hospital admissions (large)', years:'2004–2018', metric:'weekly admissions', tags:['line','5 series'], prompt:'Hospital admissions for five hospitals in a European country from 2004 to 2018.', hint:'A larger version of Graph 1 for close reading of crossings and turning points.', sample:['The line graph illustrates weekly admissions to five hospitals in a European country from 2004 to 2018.','Overall, Bardley was generally the busiest hospital, whereas Oxley experienced by far the largest decline.','Bardley rose from 200 to 270 admissions, and Adlin climbed from 120 to 250.','Oxley decreased steeply from 240 to 110 admissions.','Fortsmith peaked at 220 in 2010, fell to 190, and recovered before ending at 200.','The opposing changes may suggest that demand shifted between hospitals during the period.']},
  {id:15, title:'Goods transported in the UK', years:'1974–2002', metric:'million tonnes', tags:['line','4 modes'], prompt:'Goods transported in the UK by road, water, rail and pipeline from 1974 to 2002.', hint:'Road remains highest and rises; pipeline climbs then levels off; water and rail fluctuate.', sample:['The line graph compares goods transported in the UK by four modes from 1974 to 2002.','Overall, road carried the most goods throughout and increased further, while pipeline remained the least used mode.','Road freight rose from about 70 to 95 million tonnes, and pipeline transport grew from roughly 5 to just over 20 million tonnes.','Rail declined from 40 to around 30 million tonnes before recovering to approximately 41.','Water transport rose to nearly 60, dipped to about 50 in 1998, and then rebounded to 65.','The pattern may indicate the continuing importance of road and water freight in the UK.']},
  {id:16, title:'Sources of news', years:'1995–2025', metric:'percentage accessing news', tags:['line','projection'], prompt:'The percentage of people accessing news from TV, radio, newspapers and the Internet from 1995 to 2025.', hint:'Internet use climbs from zero; traditional sources decline, with TV remaining strongest until the end.', sample:['The line graph compares the percentages accessing news through four sources from 1995 to 2025.','Overall, Internet news rises dramatically from zero, while TV, radio and newspapers all decline.','Internet access climbs from 0% to about 55%, overtaking newspapers and radio by the end.','TV falls from roughly 68% to 50%, while radio drops from just above 50% to about 22%.','Newspaper use remains near 50% initially before declining steadily to under 30%.','The data points to a continuing shift from traditional media to online news.']},
  {id:17, title:'Women in employment', years:'2003–2009', metric:'percentage employed', tags:['line','5 countries'], prompt:'Percentages of women aged 15–64 in employment in five countries from 2003 to 2009.', hint:'Iceland remains highest; Chile and Germany rise; Turkey stays lowest.', sample:['The line graph compares employment rates among women aged 15–64 in five countries from 2003 to 2009.','Overall, Iceland consistently recorded the highest rate, whereas Turkey remained the lowest.','Chile rose from 35% to 41%, while Germany increased from 59% to 65%.','Iceland edged down from about 81% to 78% by 2009.','Turkey dipped from 25% to 22% before recovering to its starting level, while Canada stayed close to 70%.','The stable ranking suggests persistent differences in female employment across the five countries.']},
  {id:18, title:'Second languages in New Zealand', years:'2006–2014', metric:'percentage of primary students', tags:['line','6 languages'], prompt:'Percentages of New Zealand primary-school students learning six second languages from 2006 to 2014.', hint:'French stays highest; Japanese falls; Chinese rises and overtakes several languages.', sample:['The line graph shows the percentages of New Zealand primary pupils learning six second languages from 2006 to 2014.','Overall, French remained the most popular language, while Chinese grew strongly as Japanese and German declined.','Chinese rose from about 4% to 13%, overtaking German and other languages near the end.','Japanese fell substantially from 28% to 17%, and German declined from around 14% to 7%.','French fluctuated between approximately 28% and 33%, finishing close to its initial level.','The changes may indicate growing interest in Chinese alongside weakening demand for Japanese and German.']},
  {id:19, title:'India’s GDP by sector', years:'1960–2000', metric:'percentage contribution to GDP', tags:['bar','3 sectors'], prompt:'Agriculture, industry and services as shares of India’s GDP from 1960 to 2000.', hint:'Agriculture declines; services rise to become largest; industry increases modestly.', sample:['The bar chart compares the contributions of agriculture, industry and services to India’s GDP from 1960 to 2000.','Overall, agriculture declined dramatically, while services rose to become the largest sector; industry changed more modestly.','Services increased from about 17% to 63%, and industry grew from roughly 16% to 25%.','Agriculture more than halved, falling from approximately 63% to 14%.','The service share rose steadily, with particularly strong growth after 1980.','The figures indicate a long-term structural shift in India’s economy from agriculture towards services.']},
  {id:20, title:'Five portions of fruit and vegetables', years:'2001–2008', metric:'percentage of people', tags:['bar','3 groups'], prompt:'Percentages of men, women and children in the UK who ate five portions of fruit and vegetables per day from 2001 to 2008.', hint:'All three groups rise to a late peak then ease; women remain highest throughout.', sample:['The bar chart illustrates the percentages of UK men, women and children eating five daily portions of fruit and vegetables from 2001 to 2008.','Overall, women consistently recorded the highest proportions, while children remained the lowest; all groups rose before easing near the end.','Children’s figure more than doubled from about 12% to 26%, while men’s rose from 17% to around 29%.','After their peaks, the figures slipped to roughly 24% for children, 27% for men and 31% for women in 2008.','Women’s proportion climbed from 21% to a peak of about 34% in 2006 before declining slightly.','The broad rise may indicate increasing awareness of healthy eating during the period.']}
];

const SITE_CONFIG = {
  reviewEndpoint: '',
  teacherName: 'Jennifer',
  graphType: 'Trends: increase, decrease & fluctuation'
};
